name: "Check pull request body, diff and files - Copy"
description: "Checks that the body or the added code contains or avoid a word, number of files or lines changed"
author: "JJ"
branding:
  icon: "git-pull-request"
  color: "gray-dark"
inputs:
  github-token:
    description: "Github token, added magically"
  bodyContains:
    description: "String or |-separated array of strings, one of which must be contained in the PR body, can be left blank or omitted"
  bodyDoesNotContain:
    description: "String or |-separated array of strings, none of which should be in the PR body, can be left blank"
  diffContains:
    description: "Word that must be contained in the added code"
  diffDoesNotContain:
    description: "Word that should not be contained in the added code"
  linesChanged:
    description: "Max number of lines changed per PR"
  filesChanged:
    description: "Max number of files changed in the PR"
  waivedUsers:
    description: "Users that will not need to follow these guidelines. Defaults to dependabot."
outputs:
  diff:
    description: "Lines added to the PR"

runs:
  using: "node16"
  main: "dist/index.js"
