name: "Check pull request body, diff and files"
description: "Checks that the body or the added code contains or avoids a word, number of files or lines changed"
author: "JJ"
branding:
  icon: "git-pull-request"
  color: "gray-dark"
inputs:
  github-token:
    description: "Github token, added magically"
  allowEmpty:
    description: "Boolean - true will only throw a warning if the body is empty, false will fail the run. Defaults to true."
    default: true
  bodyContains:
    description: "String or |-separated array of strings, one of which must be contained in the PR body, can be left blank or omitted"
  bodyDoesNotContain:
    description: "String or |-separated array of strings, none of which should be in the PR body, can be left blank"
  diffContains:
    description: "Word that must be included in the added code"
  diffDoesNotContain:
    description: "Word that should not be in the added code"
  linesChanged:
    description: "Exact number of lines changed per PR"
  filesChanged:
    description: "Exact number of files changed in the PR"
  waivedUsers:
    description: "Users that will not need to follow these guidelines, separated by |. Defaults to dependabot."
outputs:
  diff:
    description: "Lines added to the PR"
  numberOfFiles:
    description: "Number of files changed in the PR"

runs:
  using: "node20"
  main: "dist/index.js"
