name: Check correct version
on:
  push:

jobs:
  check_v_in_example:
    runs-on: ubuntu-latest
    name: Test version
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check version
      uses: JJ/github-action-check-version-in-readme-is-latest@main
