name: "Check contributors file additions"
on:
  pull_request:
    types: [opened, edited]
    paths:
      - CONTRIBUTORS.md

jobs:
  check_pr:
    name: "Checks contributors"
    runs-on: ubuntu-latest
    steps:
      - name: Check PR for single contributots with link
        uses: JJ/github-pr-contains-action@releases/v12
        with:
          github-token: ${{github.token}}
          linesChanged: 1
          filesChanged: 1
          diffContains: github.com/
